ciall: Abort if "--" was specified and no text was entered
89873656-192b-11e0-a938-00023faf1383

diff --git a/ciall b/ciall
--- a/ciall
+++ b/ciall
@@ -27,6 +27,7 @@ if [ "$logmsg" = "--" ]; then
     tmpmsgfile=/tmp/$(date +%s)-$$.tmp
     $EDITOR $tmpmsgfile
     logmsg=$(cat $tmpmsgfile)
+    test -z "$logmsg" && { echo ciall: No text entered in editor, aborting.; exit 1; }
 fi
 
 LC_ALL=C git status | grep "^nothing to commit" || (git add . && git commit -a -m "$logmsg`echo; echo; suuid -t ciall -c "$logmsg"`")
