filesynced: Add --timeout option, maximum time to wait for lock
dfb82e3a-b120-11e5-abd7-fefdb24f8e10

diff --git a/filesynced b/filesynced
--- a/filesynced
+++ b/filesynced
@@ -32,6 +32,7 @@ lock,\
 set-priority:,\
 quiet,\
 random,\
+timeout:,\
 type:,\
 unlock,\
 verbose,\
@@ -47,6 +48,7 @@ opt_lock=0
 opt_set_priority=''
 opt_quiet=0
 opt_random=0
+opt_timeout=''
 opt_type='%'
 opt_unlock=0
 opt_verbose=0
@@ -59,6 +61,7 @@ while :; do
         (-p|--set-priority) opt_set_priority=$2; shift 2 ;;
         (-q|--quiet) opt_quiet=$(($opt_quiet + 1)); shift ;;
         (--random) opt_random=1; shift ;;
+        (--timeout) opt_timeout=$2; shift 2 ;;
         (-t|--type) opt_type=$2; shift 2 ;;
         (--unlock) opt_unlock=1; shift ;;
         (-v|--verbose) opt_verbose=$(($opt_verbose + 1)); shift ;;
@@ -103,6 +106,9 @@ Options:
     Be more quiet. Can be repeated to increase silence.
   --random
     Pick a random file from the todo list and sync it using "vd".
+  --timeout SECONDS
+    Wait maximum SECONDS seconds for lock. Default is no timeout, wait 
+    until it gets the lock or the script is forcibly terminated.
   -t FILETYPE. --type FILETYPE
     Limit list to files of type FILETYPE, for example "bash" or 
     "perl-tests". SQL LIKE wildcards can be used, like '%' and '_'.
@@ -140,6 +146,13 @@ msg() {
 }
 
 msg -l 2 Starting $progname, pwd = $(pwd)
+
+if test -n "$opt_timeout"; then
+    if test -n "$(echo "$opt_timeout" | tr -d 0-9 | grep .)"; then
+        echo $progname: Argument to --timeout must be an integer >&2
+        exit 1
+    fi
+fi
 
 repotop="$(git rev-parse --show-toplevel)"
 msg 2 repotop = \"$repotop\"
@@ -213,8 +226,18 @@ if test "$opt_lock" = "1"; then
         echo $progname --lock: $repotop: chdir error >&2
         exit 1
     }
+    begin_wait_time=$(date -u +%s)
     until mkdir "$lockdir" 2>/dev/null; do
         echo $progname --lock: $lockdir: Waiting for lockdir... >&2
+        if test -n "$opt_timeout" -a \
+          $(( $(date -u +%s) - $begin_wait_time )) -gt \
+          $(( $opt_timeout - 1 )); then
+            printf '%s: Lock not aquired after %u second%s, aborting\n' >&2 \
+                "$progname" \
+                "$opt_timeout" \
+                "$(test "$opt_timeout" = "1" || echo -n s)"
+            exit 1
+        fi
         sleep 2
     done
     if test -e "$db"; then
@@ -278,7 +301,7 @@ if test "$opt_unlock" = "1"; then
 fi
 
 bintoken=
-token=$(filesynced --lock)
+token=$(filesynced --lock --timeout "$opt_timeout")
 if test -z "$(echo $token | grep ^token_)"; then
     echo $progname: No token received from filesynced --lock >&2
     exit 1
