log_df: Store entries with SQLite in ~/log/df.sqlite
c43528c8-88af-11e5-8797-fefdb24f8e10

diff --git a/log_df b/log_df
--- a/log_df
+++ b/log_df
@@ -56,16 +56,83 @@ END
     exit 0
 fi
 
-logdir=$HOME/log
+SQLITE=sqlite3
+logdir="$HOME/log"
+db="$logdir/df.sqlite"
 
-[ -d $logdir ] || mkdir -p logdir || { echo "mkdir $logdir: På trynet" >&2; exit 1; }
-[ -x /usr/bin/cronolog ] || { echo "Fant ikke /usr/sbin/cronolog, avbryter." >&2; exit 1; }
+[ -d "$logdir" ] || mkdir -p "$logdir" || {
+    echo "$progname: $logdir: Could not create directory" >&2
+    exit 1
+}
+[ -r "$logdir/.disks" ] || {
+    echo "$progname: $logdir/.disks: File not found, aborting" >&2
+    exit 1
+}
 
-[ -r $logdir/.disks ] || { echo "$logdir/.disks finnes ikke, avbryter." >&2; exit 1; }
+if test ! -f "$db"; then
+    cat <<END | $SQLITE "$db"
+CREATE TABLE df (
+  date TEXT
+    CONSTRAINT df_date_length
+      CHECK (length(date) = 19)
+    CONSTRAINT df_date_valid
+      CHECK (datetime(date) IS NOT NULL)
+    NOT NULL
+  ,
+  mountp TEXT
+    CONSTRAINT df_mountp_length
+      CHECK (length(mountp) > 0)
+    NOT NULL
+  ,
+  device TEXT
+    CONSTRAINT df_device_length
+      CHECK (length(device) > 0)
+    NOT NULL
+  ,
+  size INTEGER
+    CONSTRAINT df_size_positive
+      CHECK (size > 0)
+    NOT NULL
+  ,
+  used INTEGER
+    CONSTRAINT df_used_positive
+      CHECK (used > 0)
+    NOT NULL
+  ,
+  free INTEGER
+    CONSTRAINT df_free_length
+      CHECK (length(free) > 0)
+    NOT NULL
+  ,
+  percent REAL
+    CONSTRAINT df_percent_length
+      CHECK (length(percent) > 0)
+    NOT NULL
+);
+END
+fi
 
-df -P `cat $logdir/.disks` |
+df -B 1 -P $(cat "$logdir/.disks") |
     grep / |
-    uniq |
-    perl -pe 'chomp(my $a = `date -u +"%Y-%m-%dT%H:%M:%SZ"`); s/^/$a /;' |
-    /usr/bin/cronolog -z 0 -S $logdir/curr_df $logdir/df/%Y/%Y-%m-%d.df.log
-~/bin/log_df_pg
+    sort -u |
+    perl -e "
+while (<>) {
+    chomp();
+    if (/^(\\S+)\\s+(\\d+)\\s+(\\d+)\\s+(\\d+)\\s+(\\S+)%\\s+(\\S+)\$/) {
+        my (\$device, \$size, \$used, \$free, \$percent, \$mountp) =
+            (\$1, \$2, \$3, \$4, \$5, \$6);
+        print(
+            \"INSERT INTO df \" .
+            \"(date, mountp, device, size, used, free, percent) \" .
+            \"VALUES (\" .
+            \"datetime('now'), '\$mountp', '\$device', \" .
+            \"\$size, \$used, \$free, \$percent\" .
+            \");\\n\" .
+            \"\" .
+            \"\"
+        );
+    } else {
+        warn(\"$progname: Invalid line: \\"\$_\\"\\n\");
+    }
+}
+" | $SQLITE "$db"
