Legger inn sjekk i alle programmer i /trunk/ (ikke underkataloger) som bruker suuid(1) for at det gikk bra.
* /trunk/bigsh
  Hvis suuid ikke gikk bra, sender den melding til stderr, en med 
  xmessage(1) (som har en layout som jeg ikke liker), og tar en exit 1.

* /trunk/fileid
* /trunk/getsvnfiles
* /trunk/logging
* /trunk/mkFiles
* /trunk/mkt
* /trunk/n95film
* /trunk/sess
* /trunk/std
* /trunk/stpl
* /trunk/ti
* /trunk/upd
* /trunk/v
* /trunk/vg
* /trunk/wav_to_flac
  Her sjekkes det at man mottok en lovlig UUID, og hvis det gikk på 
  trynet, avbrytes scriptet. Noen har også fått seg File ID.

* /trunk/radiolagring
  Det sjekkes her også, men den fortsetter. Man føkker ikke opp 
  downloaden fordi man ikke klarer å lage uuid.

a7502010-0903-11de-b568-000475e441b9

git-svn-id: svn+ssh://svnhost/utils@3031 ddca7c6a-6bd8-0310-abd8-a0f6a7c394c1

diff --git a/logging b/logging
--- a/logging
+++ b/logging
@@ -6,7 +6,7 @@
 export LOGDIR=$HOME/log/script
 [ -d $LOGDIR/. ] || mkdir -p $LOGDIR || { echo logging: $LOGDIR: Cannot create log directory >&2; exit 1; }
 export LDATE=`u`
-uuid=`suuid -t logging -w eo -c "logging $*"`
+uuid=`suuid -t logging -w eo -c "logging $*"` || { echo logging: Error when generating UUID, logging not started >&2; exit 1; }
 if [ -z "$1" ]; then
     export LNAME="$LOGDIR/$LDATE.$uuid"
 else
diff --git a/mkt b/mkt
--- a/mkt
+++ b/mkt
@@ -2,6 +2,7 @@
 
 # Creates a .tar.gz file of current directory
 # $Id$
+# File ID: dc74ffde-08f1-11de-a419-000475e441b9
 # (C)opyleft 1999- sunny@sunbase.org
 # License: GNU General Public License version 2 or later
 
@@ -86,7 +87,8 @@ fi
 HOSTN="`hostname`"
 CURRDIR="`/bin/pwd`"
 cd .. || { echo "$0: Cannot \"cd ..\"" >&2; exit 1; }
-tar cf $_prefix.tar --label=`suuid -t mkt -w eo -c "Created $_prefix.tar$_packext with mkt(1) of directory $HOSTN:$CURRDIR/"` $_prefix || { echo "$0: Error running \"tar cf $_prefix.tar $_prefix\" in parent dir" >&2; exit 1; }
+uuid=`suuid -t mkt -w eo -c "Created $_prefix.tar$_packext with mkt(1) of directory $HOSTN:$CURRDIR/"` || { echo $0: suuid error >&2; exit 1; }
+tar cf $_prefix.tar --label=$uuid $_prefix || { echo "$0: Error running \"tar cf $_prefix.tar $_prefix\" in parent dir" >&2; exit 1; }
 
 if [ "$_no_compress" -eq "1" ]; then
 	exit 0
