* /trunk/mkt   Var en forandring i suuid-kommentaren som jeg glemte i farta. «in» →   «of». Irriterende.
0b116672-7e0d-11dd-b421-000475e441b9


git-svn-id: svn+ssh://svnhost/utils@2406 ddca7c6a-6bd8-0310-abd8-a0f6a7c394c1

diff --git a/mkt b/mkt
--- a/mkt
+++ b/mkt
@@ -86,7 +86,7 @@ fi
 HOSTN="`hostname`"
 CURRDIR="`/bin/pwd`"
 cd .. || { echo "$0: Cannot \"cd ..\"" >&2; exit 1; }
-tar cf $_prefix.tar --label=`suuid -t mkt -c "Created $_prefix.tar$_packext with mkt(1) in directory $HOSTN:$CURRDIR/"` $_prefix || { echo "$0: Error running \"tar cf $_prefix.tar $_prefix\" in parent dir" >&2; exit 1; }
+tar cf $_prefix.tar --label=`suuid -t mkt -c "Created $_prefix.tar$_packext with mkt(1) of directory $HOSTN:$CURRDIR/"` $_prefix || { echo "$0: Error running \"tar cf $_prefix.tar $_prefix\" in parent dir" >&2; exit 1; }
 
 if [ "$_no_compress" -eq "1" ]; then
 	exit 1;
