mkt: Use "tar --sort=name" instead of piping find(1) output to tar
This option is pretty new, it was added to tar.git in revision
release_1_27_1-22-g29a6964, commit 29a6964 ("New option --sort=ORDER",
2014-02-14), so be prepared to roll yer own to make it work.

762fa220-2387-11e6-a3ca-02010e0a6634

diff --git a/mkt b/mkt
--- a/mkt
+++ b/mkt
@@ -11,7 +11,7 @@
 #=======================================================================
 
 progname=mkt
-VERSION=0.1.0
+VERSION=0.2.0
 
 ARGS="$(getopt -o "\
 g\
@@ -141,13 +141,10 @@ uuid=$(
     echo $progname: suuid error >&2
     exit 1
 }
-find "$_prefix" -print0 |
-    LC_COLLATE=C sort -z |
-    tar cf "$_prefix.tar" --null -T - \
-        --no-recursion --label=$uuid "$_prefix" || {
-            echo "$progname: Error running tar in parent dir" >&2
-            exit 1
-        }
+tar cf "$_prefix.tar" --label=$uuid "$_prefix" --sort=name || {
+    echo "$progname: Error running tar in parent dir" >&2
+    exit 1
+}
 
 if [ "$opt_nocomp" = "1" ]; then
 	exit 0
