mkt: Sync against Lib/std/bash + rewrite the thing
Ended up rewriting most of it, there were some old bad habits there:

  - Make it use getopt
  - Remove unnecessary variables now that $opt_* are in da house
  - Quote variables to allow bloody whitespace in filenames
  - Break long lines
  - Use $() instead of backticks

There are some minor things left, like getting rid of some bashisms, but
this commit is too big already.

0186dc10-237b-11e6-97fe-02010e0a6634

diff --git a/mkt b/mkt
--- a/mkt
+++ b/mkt
@@ -1,124 +1,190 @@
 #!/bin/bash
 
-# Creates a .tar.gz file of current directory
+#=======================================================================
 # mkt
 # File ID: dc74ffde-08f1-11de-a419-000475e441b9
-# (C)opyleft 1999- sunny@sunbase.org
-# License: GNU General Public License version 2 or later
+#
+# Creates a .tar.gz file of current directory
+#
+# Author: Øyvind A. Holm <sunny@sunbase.org>
+# License: GNU General Public License version 2 or later.
+#=======================================================================
 
-# FIXME: Finn ut av -r kombinert med -n
+progname=mkt
+VERSION=0.1.0
 
-if [ "x$1" = "x--help" -o "x$1" = "x-h" ]; then
-	cat <<END
+ARGS="$(getopt -o "\
+g\
+h\
+n\
+q\
+r\
+v\
+" -l "\
+gpg,\
+help,\
+nocomp,\
+quiet,\
+remove,\
+verbose,\
+version,\
+" -n "$progname" -- "$@")"
+test "$?" = "0" || exit 1
+eval set -- "$ARGS"
 
-Usage: $0 [options] name_without_the_tar_gz_extension
+opt_gpg=0
+opt_help=0
+opt_nocomp=0
+opt_quiet=0
+opt_remove=0
+opt_verbose=0
+while :; do
+    case "$1" in
+        (-g|--gpg) opt_gpg=1; shift ;;
+        (-h|--help) opt_help=1; shift ;;
+        (-n|--nocomp) opt_nocomp=1; shift ;;
+        (-q|--quiet) opt_quiet=$(($opt_quiet + 1)); shift ;;
+        (-r|--remove) opt_remove=1; shift ;;
+        (-v|--verbose) opt_verbose=$(($opt_verbose + 1)); shift ;;
+        (--version) echo $progname $VERSION; exit 0 ;;
+        (--) shift; break ;;
+        (*) echo $progname: Internal error >&2; exit 1 ;;
+    esac
+done
+opt_verbose=$(($opt_verbose - $opt_quiet))
 
-Creates a .tar.gz file of current directory tree and places it in
-parent directory. If nothing is specified, current dir is used.
+if test "$opt_help" = "1"; then
+    test $opt_verbose -gt 0 && { echo; echo $progname $VERSION; }
+    cat <<END
+
+Creates a .tar.gz file of current directory tree and places it in parent 
+directory. If nothing is specified, current dir is used.
+
+Usage: $progname [options] name_without_the_tar_gz_extension
 
 Options:
 
--g, --gpg     Use gpg instead of gzip
--h, --help    Print this help message
--n, --nocomp  No compression, leave as .tar
--r, --remove  Remove directory after packing
-
-Options has to be specified in alphabethical order at the moment.
+  -g, --gpg
+    Use gpg instead of gzip.
+  -h, --help
+    Show this help.
+  -n, --nocomp
+    No compression, leave as .tar .
+  -q, --quiet
+    Be more quiet. Can be repeated to increase silence.
+  -r, --remove
+    Remove directory after packing.
+  -v, --verbose
+    Increase level of verbosity. Can be repeated.
+  --version
+    Print version information.
 
 END
-	exit 1
+    exit 0
 fi
 
-if [ "x$1" = "x--gpg" -o "x$1" = "x-g" ]; then
+# FIXME: Finn ut av -r kombinert med -n
+
+if [ "$opt_gpg" = "1" ]; then
 	_packcmd="gpg -e"
 	_packext=".gpg"
-	shift
 else
 	_packcmd="gzip -vN"
 	_packext=".gz"
 fi
 
-if [ "x$1" = "x--nocomp" -o "x$1" = "x-n" ]; then
-	_no_compress=1
+if [ "$opt_nocomp" = "1" ]; then
 	unset _packext
-	shift
-else
-	_no_compress=0
-fi
-
-if [ "x$1" = "x--remove" -o "x$1" = "x-r" ]; then
-	_can_erase=1
-	shift
-else
-	_can_erase=0
 fi
 
 if [ $# -eq 0 ]; then
-	_pwd=`pwd`
-	_prefix=`basename $_pwd`
+	_prefix="$(basename "$(pwd)")"
 else
-	_prefix=`basename $1`
+	_prefix="$(basename "$1")"
 fi
 
-if [ -e ../$_prefix.tar -o -e ../$_prefix.tar$_packext ]; then
-	echo $0: ../$_prefix.tar or ../$_prefix.tar$_packext already exists >&2
+if [ -e "../$_prefix.tar" -o -e "../$_prefix.tar$_packext" ]; then
+	echo $progname: ../$_prefix.tar or ../$_prefix.tar$_packext \
+        already exists >&2
 	exit 1
 fi
 
-if [ -e ../$_prefix -a ! ../$_prefix -ef . ]; then
-	echo $0: ../$_prefix and current dir are not the same >&2
+if [ -e "../$_prefix" -a ! "../$_prefix" -ef . ]; then
+	echo $progname: ../$_prefix and current dir are not the same >&2
 	exit 1
 fi
 
-if [ -e ../$_prefix -a ! -d ../$_prefix ]; then
-	echo $0: ../$_prefix: Not a directory >&2
+if [ -e "../$_prefix" -a ! -d "../$_prefix" ]; then
+	echo $progname: ../$_prefix: Not a directory >&2
 	exit 1
 fi
 
-if [ ! -e ../$_prefix ]; then
-	cp -a . ../$_prefix || { echo "$0: Error running \"cp -a . ../$_prefix\"" >&2; exit 1; }
+if [ ! -e "../$_prefix" ]; then
+	cp -a . "../$_prefix" || {
+        echo "$progname: Error running \"cp -a . ../$_prefix\"" >&2
+        exit 1
+    }
 fi
 
-if [ ! -d ../$_prefix ]; then
-	echo $0: Unable to create directory ../$_prefix >&2
+if [ ! -d "../$_prefix" ]; then
+	echo $progname: Unable to create directory ../$_prefix >&2
 	exit 1
 fi
 
-HOSTN="`hostname`"
-CURRDIR="`/bin/pwd`"
-cd .. || { echo "$0: Cannot \"cd ..\"" >&2; exit 1; }
-uuid=`suuid -m -t mkt --raw -w eo -c "<c_mkt> <filename>$_prefix.tar$_packext</filename> <host>$HOSTN</host> <directory>$CURRDIR</directory> </c_mkt>"` || { echo $0: suuid error >&2; exit 1; }
-find $_prefix -print0 | LC_COLLATE=C sort -z | tar cf $_prefix.tar --null -T - --no-recursion --label=$uuid $_prefix || { echo "$0: Error running tar in parent dir" >&2; exit 1; }
+cd .. || { echo "$progname: Cannot \"cd ..\"" >&2; exit 1; }
+uuid=$(
+    suuid -m -t mkt --raw -w eo \
+        -c "<c_mkt> <filename>$_prefix.tar$_packext</filename> <host>$(
+            hostname
+        )</host> <directory>$(/bin/pwd)</directory> </c_mkt>"
+) || {
+    echo $progname: suuid error >&2
+    exit 1
+}
+find "$_prefix" -print0 |
+    LC_COLLATE=C sort -z |
+    tar cf "$_prefix.tar" --null -T - \
+        --no-recursion --label=$uuid "$_prefix" || {
+            echo "$progname: Error running tar in parent dir" >&2
+            exit 1
+        }
 
-if [ "$_no_compress" -eq "1" ]; then
+if [ "$opt_nocomp" = "1" ]; then
 	exit 0
 fi
 
-$_packcmd $_prefix.tar || { echo "$0: Error running \"$_packcmd $_prefix.tar\" in parent dir" >&2; exit 1; }
+$_packcmd "$_prefix.tar" || {
+    echo "$progname: Error running \"$_packcmd $_prefix.tar\" \
+        in parent dir" >&2
+    exit 1
+}
 
 if [ "$_packext" = ".gpg" ]; then
-	gitwipe $_prefix.tar
+	gitwipe "$_prefix.tar"
 	sync
-	rm -f $_prefix.tar
+	rm -f "$_prefix.tar"
 fi
 
-if [ "$_can_erase" -eq "1" ]; then
-	rm -rf $_prefix || { echo "$0: $_prefix: Can't remove directory" >&2; exit 1; }
+if [ "$opt_remove" = "1" ]; then
+	rm -rf "$_prefix" || {
+        echo "$progname: $_prefix: Can't remove directory" >&2
+        exit 1
+    }
 fi
 
 # This program is free software; you can redistribute it and/or modify 
 # it under the terms of the GNU General Public License as published by 
 # the Free Software Foundation; either version 2 of the License, or (at 
 # your option) any later version.
-# 
+#
 # This program is distributed in the hope that it will be useful, but 
 # WITHOUT ANY WARRANTY; without even the implied warranty of 
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 # See the GNU General Public License for more details.
-# 
+#
 # You should have received a copy of the GNU General Public License 
 # along with this program; if not, write to the Free Software 
-# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  
+# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 
 # USA
 
 #### End of file mkt ####
