* /trunk/mkt   - Debian bruker bash 2.01, og der er det litt inkompatibilitet. Måtte     legge til et semikolon inne i alle "{ }"’er når "||" ble brukt.   - Forandra email til sunny@pils.kvarteret.uib.no
git-svn-id: svn+ssh://svnhost/utils@98 ddca7c6a-6bd8-0310-abd8-a0f6a7c394c1

diff --git a/mkt b/mkt
--- a/mkt
+++ b/mkt
@@ -1,8 +1,8 @@
 #!/bin/bash
 
 # Creates a .tar.gz file of current directory
-# $Id: mkt,v 1.3 1999/05/05 02:33:18 sunny Exp $
-# (C)opyleft 1999 sunny@dataguard.no
+# $Id: mkt,v 1.4 1999/09/01 15:43:21 sunny Exp $
+# (C)opyleft 1999 sunny@pils.kvarteret.uib.no
 # License: GNU GPL
 
 if [ "x$1" = "x--help" -o "x$1" = "x-h" ]; then
@@ -52,7 +52,7 @@ if [ -e ../$_prefix -a ! -d ../$_prefix ]; then
 fi
 
 if [ ! -e ../$_prefix ]; then
-	cp -a . ../$_prefix || { echo "$0: Error running \"cp -a . ../$_prefix\"" >&2; exit 1 }
+	cp -a . ../$_prefix || { echo "$0: Error running \"cp -a . ../$_prefix\"" >&2; exit 1; }
 fi
 
 if [ ! -d ../$_prefix ]; then
@@ -60,11 +60,11 @@ if [ ! -d ../$_prefix ]; then
 	exit 1
 fi
 
-cd .. || { echo "$0: Cannot \"cd ..\"" >&2; exit 1 }
-tar cf $_prefix.tar $_prefix || { echo "$0: Error running \"tar cf $_prefix.tar $_prefix\" in parent dir" >&2; exit 1 }
-gzip -vN $_prefix.tar || { echo "$0: Error running \"gzip -vN $_prefix.tar\" in parent dir" >&2; exit 1 }
+cd .. || { echo "$0: Cannot \"cd ..\"" >&2; exit 1; }
+tar cf $_prefix.tar $_prefix || { echo "$0: Error running \"tar cf $_prefix.tar $_prefix\" in parent dir" >&2; exit 1; }
+gzip -vN $_prefix.tar || { echo "$0: Error running \"gzip -vN $_prefix.tar\" in parent dir" >&2; exit 1; }
 if [ "$_can_erase" -eq "1" ]; then
-	rm -rf $_prefix || { echo "$0: $_prefix: Can't remove directory" >&2; exit 1 }
+	rm -rf $_prefix || { echo "$0: $_prefix: Can't remove directory" >&2; exit 1; }
 fi
 
-#### End of file $Id: mkt,v 1.3 1999/05/05 02:33:18 sunny Exp $ ####
+#### End of file $Id: mkt,v 1.4 1999/09/01 15:43:21 sunny Exp $ ####
