La til "-g"-parameteret som bruker gpg istedenfor gzip.
git-svn-id: svn+ssh://svnhost/utils@149 ddca7c6a-6bd8-0310-abd8-a0f6a7c394c1

diff --git a/mkt b/mkt
--- a/mkt
+++ b/mkt
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 # Creates a .tar.gz file of current directory
-# $Id: mkt,v 1.4 1999/09/01 15:43:21 sunny Exp $
+# $Id: mkt,v 1.5 2000/07/13 09:18:51 sunny Exp $
 # (C)opyleft 1999 sunny@pils.kvarteret.uib.no
 # License: GNU GPL
 
@@ -15,11 +15,21 @@ parent directory. If nothing is specified, current dir is used.
 
 Options:
 
+-g, --gpg     Use gpg instead of gzip
 -h, --help    Print this help message
 -r, --remove  Remove directory after packing
 
 END
 	exit 1
+fi
+
+if [ "x$1" = "x--gpg" -o "x$1" = "x-g" ]; then
+	_packcmd="gpg -e"
+	_packext=".gpg"
+	shift
+else
+	_packcmd="gzip -vN"
+	_packext=".gz"
 fi
 
 if [ "x$1" = "x--remove" -o "x$1" = "x-r" ]; then
@@ -36,8 +46,8 @@ else
 	_prefix=`basename $1`
 fi
 
-if [ -e ../$_prefix.tar -o -e ../$_prefix.tar.gz ]; then
-	echo $0: ../$_prefix.tar or ../$_prefix.tar.gz already exists >&2
+if [ -e ../$_prefix.tar -o -e ../$_prefix.tar$_packext ]; then
+	echo $0: ../$_prefix.tar or ../$_prefix.tar$_packext already exists >&2
 	exit 1
 fi
 
@@ -62,9 +72,14 @@ fi
 
 cd .. || { echo "$0: Cannot \"cd ..\"" >&2; exit 1; }
 tar cf $_prefix.tar $_prefix || { echo "$0: Error running \"tar cf $_prefix.tar $_prefix\" in parent dir" >&2; exit 1; }
-gzip -vN $_prefix.tar || { echo "$0: Error running \"gzip -vN $_prefix.tar\" in parent dir" >&2; exit 1; }
+$_packcmd $_prefix.tar || { echo "$0: Error running \"$_packcmd $_prefix.tar\" in parent dir" >&2; exit 1; }
+
+if [ "$_packext" = ".gpg" ]; then
+	rm -f $_prefix.tar
+fi
+
 if [ "$_can_erase" -eq "1" ]; then
 	rm -rf $_prefix || { echo "$0: $_prefix: Can't remove directory" >&2; exit 1; }
 fi
 
-#### End of file $Id: mkt,v 1.4 1999/09/01 15:43:21 sunny Exp $ ####
+#### End of file $Id: mkt,v 1.5 2000/07/13 09:18:51 sunny Exp $ ####
