* /trunk/scrdump   Gjorde den mer universal. Fjerna all hardkoding (sunny-brukeren og   ~/bin/u). Nå kaller den date(1) direkte. Forandra shebangen til   /bin/bash. I tillegg lager den $scrdumpdir (som også er ny) hvis den   ikke finnes fra før.
git-svn-id: svn+ssh://svnhost/utils@2186 ddca7c6a-6bd8-0310-abd8-a0f6a7c394c1

diff --git a/scrdump b/scrdump
--- a/scrdump
+++ b/scrdump
@@ -1,8 +1,13 @@
-#!/bin/sh
+#!/bin/bash
 
 #=======================================================================
 # $Id$
 # Skjermdump i X.
 #=======================================================================
 
-import -w root ~sunny/screendumps/$(~/bin/u).$(hostname)-screendump.png
+scrdumpdir=$HOME/screendumps
+
+[ -d $scrdumpdir/. ] || mkdir $scrdumpdir || { echo "$0: $scrdumpdir: Cannot create directory" >&2; exit 1; }
+
+# import-programmet hører med til ImageMagick.
+import -w root $scrdumpdir/$(date -u +"%Y%m%dT%H%M%SZ").$(hostname)-screendump.png
