* /trunk/sub-mergesvn   Funker forsåvidt greit, men det er potensielt trøbbel med filnavn som   inneholder space. Men der er det noe rusk i mergesvn også, ser det ut   til. Nøye då. Man bruker ikke sånt.
e078394e-f9f0-11dd-8b2b-000475e441b9


git-svn-id: svn+ssh://svnhost/utils@2893 ddca7c6a-6bd8-0310-abd8-a0f6a7c394c1

diff --git a/sub-mergesvn b/sub-mergesvn
--- a/sub-mergesvn
+++ b/sub-mergesvn
@@ -3,8 +3,13 @@
 #=======================================================================
 # $Id$
 # File ID: 346a3428-f9ef-11dd-8b2b-000475e441b9
-# [Description]
+# Execute mergesvn(1) on all files in current directory tree.
 # License: GNU General Public License version 2 or later.
 #=======================================================================
 
-
+for f in `find -type d | ns | sort`; do
+    echo "=========== $f ===========";
+    (cd "$f" \
+        && (find . -maxdepth 1 -type f | xargs mergesvn) \
+        || echo "$f: cannot chdir");
+done
