* /trunk/svnclean   La inn sjekk for at nåværende katalog er en svn-arbeidskopi + gjorde   advarselen mer informativ. Og sendte noe til stderr som gikk til   stdout.
d10d03be-881b-11dd-816f-000475e441b9


git-svn-id: svn+ssh://svnhost/utils@2473 ddca7c6a-6bd8-0310-abd8-a0f6a7c394c1

diff --git a/svnclean b/svnclean
--- a/svnclean
+++ b/svnclean
@@ -6,8 +6,14 @@
 # License: GNU General Public License version 2 or later.
 #=======================================================================
 
-echo "Warning, this command will clean out all non-versioned files." >&2
-echo -n "Press 'y' + Enter to continue..."
+if [ ! -d .svn/. ]; then
+    echo "Current directory is not a svn working copy, aborting." >&2
+    exit 1
+fi
+
+echo Warning, this command will delete all files which is not versioned with >&2
+echo Subversion. The working copy will be reset. >&2
+echo -n "Press 'y' + Enter to continue..." >&2
 read choice
 if [ "$choice" = "y" ]; then
     echo ==== svn cleanup...
