* /trunk/vg   Den er forfremmet til Perl, det ble for krøkkete å styre på i bash med   de greiene som skal legges inn. Voldsomt provisoriske greier, men det   funker. Foreløpig er det den samme funksjonaliteten som var, med   unntak av at den leverer ting i XML til suuid.
af2d2fe2-0f95-11de-a023-000475e441b9

git-svn-id: svn+ssh://svnhost/utils@3078 ddca7c6a-6bd8-0310-abd8-a0f6a7c394c1

diff --git a/vg b/vg
--- a/vg
+++ b/vg
@@ -1,32 +1,248 @@
-#!/bin/bash
+#!/usr/bin/perl -w
 
+#=======================================================================
 # $Id$
 # File ID: 58ece940-08f3-11de-ab14-000475e441b9
+# View GPX files in gnuplot(1)
+#
+# Character set: UTF-8
+# ©opyleft 2009– Øyvind A. Holm <sunny@sunbase.org>
+# License: GNU General Public License version 2 or later, see end of 
+# file for legal stuff.
+#=======================================================================
 
-cmdl=$*
-uuid=`suuid -w eo -t vg -c "vg $*"` || { echo vg: suuid error >&1; exit 1; }
-if [ "$1" = "-t" ]; then
-    shift
-    (echo "# Session ID: $uuid"; gpst -o csv -rt -e -d -t "$@") | rmspcall | uniq >/tmp/vg-t.tmp
-    cat <<END >/tmp/vg-t-cmd.tmp
+BEGIN {
+    our @version_array;
+}
+
+use strict;
+use Getopt::Long;
+
+$| = 1;
+
+our $Debug = 0;
+
+our %Opt = (
+
+    'debug' => 0,
+    'help' => 0,
+    'time' => 0,
+    'verbose' => 0,
+    'version' => 0,
+
+);
+
+our $progname = $0;
+$progname =~ s/^.*\/(.*?)$/$1/;
+
+my $rcs_id = '$Id$';
+my $id_date = $rcs_id;
+$id_date =~ s/^.*?\d+ (\d\d\d\d-.*?\d\d:\d\d:\d\d\S+).*/$1/;
+
+push(@main::version_array, $rcs_id);
+my @cmdl = @ARGV;
+
+Getopt::Long::Configure("bundling");
+GetOptions(
+
+    "debug" => \$Opt{'debug'},
+    "help|h" => \$Opt{'help'},
+    "time|t" => \$Opt{'time'},
+    "verbose|v+" => \$Opt{'verbose'},
+    "version" => \$Opt{'version'},
+
+) || die("$progname: Option error. Use -h for help.\n");
+
+$Opt{'debug'} && ($Debug = 1);
+$Opt{'help'} && usage(0);
+if ($Opt{'version'}) {
+    print_version();
+    exit(0);
+}
+
+my $cmdl_str = join(" ", @cmdl);
+my $uuid=`suuid -w eo -t vg --raw -c "<c_vg> <cmdline>$cmdl_str</cmdline> </c_vg>"` || die("$progname: suuid error");
+
+if ($Opt{'time'}) {
+    my $dat_file = "/tmp/vg-t.tmp";
+    open(FP, ">$dat_file") || die("$progname: $dat_file: Cannot open file for write: $!\n");
+    print(FP "# Session ID: $uuid\n");
+    my @gpst_array = ("gpst", "-o", "csv", "-rt", "-e", "-d", "-t", @ARGV, "|", "rmspcall", "|", "uniq");
+    print(FP `@gpst_array`);
+    close(FP);
+    my $cmd_file = "/tmp/vg-t-cmd.tmp";
+    open(FP, ">$cmd_file") || die("$progname: $cmd_file: Cannot open file for write: $!\n");
+    print(FP <<END);
 # Session ID: $uuid
 set mouse
 # load "/tmp/label.gnuplot"
 set zdata time
 # set timefmt "%Y-%m-%dT%H:%M:%SZ"
 set timefmt "%s"
-splot "/tmp/vg-t.tmp" using 2:3:1 w l palette
+splot "$dat_file" using 2:3:1 w l palette
 pause -1 "Trykk Enter..."
 END
-    gnuplot -persist /tmp/vg-t-cmd.tmp
-else
-    (echo "# Session ID: $uuid"; gpst -o clean -ret -d -t "$@") | rmspcall | uniq >/tmp/vg.tmp
-    cat <<END >/tmp/vg-cmd.tmp
+    close(FP);
+    system("gnuplot -persist $cmd_file");
+} else {
+    my $dat_file = "/tmp/vg.tmp";
+    open(FP, ">$dat_file") || die("$progname: $dat_file: Cannot open file for write: $!\n");
+    print(FP "# Session ID: $uuid\n");
+    my @gpst_array = ("gpst", "-o", "clean", "-ret", "-d", "-t", @ARGV, "|", "rmspcall", "|", "uniq");
+    print(FP `@gpst_array`);
+    close(FP);
+    my $cmd_file = "/tmp/vg-cmd.tmp";
+    open(FP, ">$cmd_file") || die("$progname: $cmd_file: Cannot open file for write: $!\n");
+    print(FP <<END);
 # Session ID: $uuid
 set mouse
 # load "/tmp/label.gnuplot"
-splot "/tmp/vg.tmp" w l palette
+splot "$dat_file" w l palette
 pause -1 "Trykk Enter..."
 END
-    gnuplot -persist /tmp/vg-cmd.tmp
-fi
+    close(FP);
+    system("gnuplot -persist $cmd_file");
+}
+
+sub print_version {
+    # Print program version {{{
+    for (@main::version_array) {
+        print("$_\n");
+    }
+    # }}}
+} # print_version()
+
+sub usage {
+    # Send the help message to stdout {{{
+    my $Retval = shift;
+
+    if ($Opt{'verbose'}) {
+        print("\n");
+        print_version();
+    }
+    print(<<END);
+
+Usage: $progname [options] [file [files [...]]]
+
+Options:
+
+  -h, --help
+    Show this help.
+  -t, --time
+    Use time as Z axis instead of elevation.
+  -v, --verbose
+    Increase level of verbosity. Can be repeated.
+  --version
+    Print version information.
+  --debug
+    Print debugging messages.
+
+END
+    exit($Retval);
+    # }}}
+} # usage()
+
+sub msg {
+    # Print a status message to stderr based on verbosity level {{{
+    my ($verbose_level, $Txt) = @_;
+
+    if ($Opt{'verbose'} >= $verbose_level) {
+        print(STDERR "$progname: $Txt\n");
+    }
+    # }}}
+} # msg()
+
+sub D {
+    # Print a debugging message {{{
+    $Debug || return;
+    my @call_info = caller;
+    chomp(my $Txt = shift);
+    my $File = $call_info[1];
+    $File =~ s#\\#/#g;
+    $File =~ s#^.*/(.*?)$#$1#;
+    print(STDERR "$File:$call_info[2] $$ $Txt\n");
+    return("");
+    # }}}
+} # D()
+
+__END__
+
+# Plain Old Documentation (POD) {{{
+
+=pod
+
+=head1 NAME
+
+
+
+=head1 REVISION
+
+$Id$
+
+=head1 SYNOPSIS
+
+ [options] [file [files [...]]]
+
+=head1 DESCRIPTION
+
+
+
+=head1 OPTIONS
+
+=over 4
+
+=item B<-h>, B<--help>
+
+Print a brief help summary.
+
+=item B<-v>, B<--verbose>
+
+Increase level of verbosity. Can be repeated.
+
+=item B<--version>
+
+Print version information.
+
+=item B<--debug>
+
+Print debugging messages.
+
+=back
+
+=head1 BUGS
+
+
+
+=head1 AUTHOR
+
+Made by Øyvind A. Holm S<E<lt>sunny@sunbase.orgE<gt>>.
+
+=head1 COPYRIGHT
+
+Copyleft © Øyvind A. Holm E<lt>sunny@sunbase.orgE<gt>
+This is free software; see the file F<COPYING> for legalese stuff.
+
+=head1 LICENCE
+
+This program is free software; you can redistribute it and/or modify it 
+under the terms of the GNU General Public License as published by the 
+Free Software Foundation; either version 2 of the License, or (at your 
+option) any later version.
+
+This program is distributed in the hope that it will be useful, but 
+WITHOUT ANY WARRANTY; without even the implied warranty of 
+MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
+See the GNU General Public License for more details.
+
+You should have received a copy of the GNU General Public License along 
+with this program; if not, write to the Free Software Foundation, Inc., 
+59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
+
+=head1 SEE ALSO
+
+=cut
+
+# }}}
+
+# vim: set fenc=UTF-8 ft=perl fdm=marker ts=4 sw=4 sts=4 et fo+=w :
+# End of file $Id$
