fra-tel works, url and dest is defined in ~/.fra-telrc
cfcf4364-bb0e-11e8-9559-c75b54f489f8

diff --git a/Local/note3/fra-tel b/Local/note3/fra-tel
--- a/Local/note3/fra-tel
+++ b/Local/note3/fra-tel
@@ -4,14 +4,16 @@
 # fra-tel
 # File ID: e2b4cbf2-baff-11e8-97b6-c75b54f489f8
 #
-# [Description]
+# Send files from $url to $dest with rsync, retry until it's done.
 #
 # Author: Øyvind A. Holm <sunny@sunbase.org>
 # License: GNU General Public License version 2 or later.
 #==============================================================================
 
 progname=fra-tel
-VERSION=0.0.0
+VERSION=0.1.0
+
+rcfile=~/.fra-telrc
 
 opt_help=0
 opt_quiet=0
@@ -52,8 +54,30 @@ Options:
   --version
     Print version information.
 
+Create the rcfile and define url (ssh address of source directory) and dest 
+(local directory). For example:
+
+url=user@fromhost:/home/user/tel/
+dest=/sdcard/tel/
+
 END
 	exit 0
 fi
+
+cmd_rsync="rsync -rmvLPzz --inplace --timeout=30"
+
+unset url dest
+test -e "$rcfile" && . "$rcfile"
+
+if test -z "$url" -o -z "$dest"; then
+	echo $progname: url or dest not defined in $rcfile >&2
+	exit 1
+fi
+
+ps | grep -v "grep $cmd_rsync" | grep "$cmd_rsync" && exit 1
+until $cmd_rsync $url $dest; do
+  date;
+  sleep 2;
+done
 
 # vim: set ts=8 sw=8 sts=8 noet fo+=w tw=79 fenc=UTF-8 :
